export const types = Object.freeze({
    // Sync
    FORECAST_START_FETCHING: 'FORECAST_START_FETCHING',
    FORECAST_STOP_FETCHING: 'FORECAST_STOP_FETCHING',
    FORECAST_FILL: 'FORECAST_FILL',
    FORECAST_SET_FETCHING_ERROR: 'FORECAST_SET_FETCHING_ERROR',
    FORECAST_GET_CURRENT_DAY: 'FORECAST_GET_CURRENT',
    FORECAST_GET_FILTER: 'FORECAST_GET_FILTER',
    // Async
    FORECAST_FETCH_ASYNC: 'COMMENTS_FETCH_ASYNC',
});